### ISSUE TITLE
I have some problems

### ISSUE THREAD

**Issue by AbrnYa** [Cytoid/cytoid.io#101]
![image](https://user-images.githubusercontent.com/77602247/141671091-82a6877d-c535-4325-b96f-586bd4648ec8.png)

**Comment by Teages** [comment]
See [this file](https://github.com/Cytoid/cytoid.io/blob/master/config/development.json).

For security, I can not provide more information.

**Comment by Neo-Zhixing** [comment]
You need to have a redis instance running locally so that the SSR can sync login session status with the backend.
