### ISSUE TITLE
网站关卡封面显示不正常

### ISSUE THREAD

**Issue by snakoa** [Cytoid/cytoid.io#105]
https://cytoid.io/levels?page=4  直接打开此关卡网址 无法显示One Last Kiss 关卡图片

该关卡使用图片链接中包含小括号，无法在

`<div style="background-image:url("http://www.xxxx(YYYYYY)xxxxxxx");">`中使用

https://images.cytoid.io/levels/bundles/k8mi0K6vb2qd9c9yT4LM1A7qLgM6u0A1QFobJrv7UanM9tlWx94btXeWASYcBbrGL0/IMG_0793(20220102-122337).JPG?h=360&w=576

类似关卡：https://cytoid.io/levels/cls.reverie

https://assets.cytoid.io/levels/bundles/AKEAu5MK2JnT3IGRCda72UqJCggsDk7l7KmghZBjH0Rc5ETnhUJwkDzU1RBk7rso/Screenshot%20(242).png

**Comment by Neo-Zhixing** [comment]
Thanks for the bug report. Will fix

**Comment by Teages** [comment]
should be fixed

also new io
