### ISSUE TITLE
Simple player online status

### ISSUE THREAD

**Issue by TigerHix** [Cytoid/cytoid.io#13]
Show a simple status on a player's profile page, i.e. Online / Playing %level% / Last seen %time% ago.

This should be easily achieved with Event System.

**Comment by Neo-Zhixing** [comment]
Use the redis store for this feature.

On the server, add a global event hook and update 'player:uuid:last_activity' to a string. The key expires after a set amount of time (3600s for example)

If the key exists, we can tell that the player is active within 3600s. In that case, we can display the 'online' tag.
