### ISSUE TITLE
Collection feature improvement

### ISSUE THREAD

**Issue by Ruslan4ic** [Cytoid/cytoid.io#132]
1) The colection button on the home page says something like "Browse all *insert 3-figure number here* collections!"  but you can only see a handful collections if you actually click on it. I would like a search bar for collections or Atleast multiple pages of those hadfuls
2) Download all maps in a collection feature. Why it isn't there? It would save seconds to minutes of time! Like, that's how packs in other comunity rhythym games work! It's Nonsencical to say the least!

**Comment by Teages** [comment]
> The colection button on the home page says something like "Browse all insert 3-figure number here collections!" but you can only see a handful collections if you actually click on it. I would like a search bar for collections or Atleast multiple pages of those hadfuls

known issues, will fix in new io

> Download all maps in a collection feature. Why it isn't there? It would save seconds to minutes of time! Like, that's how packs in other comunity rhythym games work! It's Nonsencical to say the least!

Cytoid have no way to import multiple levels, so it doesn't make sense for players to download multiple levels on website at once.

but you can download multiple levels in game, just long press one level then you can select level you want to download
