### ISSUE TITLE
Event system

### ISSUE THREAD

**Issue by TigerHix** [Cytoid/cytoid.io#14]
This should be done in 2 stages:

1. (Alpha) Simple logging & reading of event objects (event name, description, data...) with a database. Events can be be polled & filtered through a REST API.

For instance, #13 can be easily implemented by:
* When a player logs in / plays a level / finishes a level & uploads a score, events are logged into the system.
* The online status can then be determined by the following pseudocode:
```
function getLastActiveTime(player) {
    return max(
        player.getEvents("logged-in").last().time,
        player.getEvents("started-game").last().time,
        player.getEvents("uploaded-score").last().time
    )
}
function getOnlineStatus(player) {
    if (CurrentTime - getLastActiveTime(player) > 30 mins) {
        return Status.Offline;
    }
    event = player.getEvents("started-game" || "uploaded-score").filter(last 30 mins).last()
    if (event != null) {
        return Status.Playing(event.level);
    } else {
        return Status.Online;
    }
}
```

2. (Beta, or even for later releases) Set up library methods so the front end can subscribe to new events and react respectfully.

**Comment by Neo-Zhixing** [comment]
Do we really need to maintain a list of events in the database? That'll blow it up pretty quickly. I think I was wrong about this previously.

What we really need is a hook system, or a "notification" system. It allows us to manage events globally at one place on the api server. Then we can selectively decided weather we want to published the event to the google pub/sub, push to some analytics service, or complete ignore the event.

For example, for #13 we can add a global hook that intercepts all events and update a number (cytoid:event:last_active) in the redis store.

**Comment by TigerHix** [comment]
Makes sense. We do need to keep all the events somewhere - imagine implementing Activity Feed. You will need every single action carried out by a user.

**Comment by Neo-Zhixing** [comment]
Then we can simply create an "activity" table and decide what are the events that needs to be pushed into this table. For now, we need to be cautious to only log the most important user activities - the activities that needs to go into the activity feed. Consider four types of user activities - logging in, new favourite, new play, and new comment.

|            | Push to followers | Push to yourself | Show on feed |
| --- | --- | --- | --- |
| Log In |  No  | When logging in from another region | No |
| New Favourite| Yes | No | Yes |
| New Play | Only when made new record | No | Yes |
| New Comment | Yes | No | No |

The point I'm trying to make is that the handling of the event might be very flexible. Some events - like logging in, a new play, or a new comment - don't always need to be recorded. For "new favourite", all you need is to publish a notification to the followers of the user with a link to the level.

Correct me if i'm missing anything.

**Comment by Neo-Zhixing** [comment]
So the event center would probably look like this:

```js
eventcenter.on('play', () => {
  // when the user breaks a new record, publish a new notification to the followers of the user.
})
eventcenter.on('play', () => {
  // when a user breaks the record on a level, publish a new notification to the followers of the level.
})
eventcenter.on('play', () => {
  // show on feed
})
```
