### ISSUE TITLE
Player region

### ISSUE THREAD

**Issue by TigerHix** [Cytoid/cytoid.io#15]
Add a sense of region-wide competitiveness, and allows features like region-specific ranking.

Needs investigation on what region system to adapt.

**Comment by Neo-Zhixing** [comment]
We should be aware that country/culture identity is a complicated problem. Problems like "is Taiwan a country or a region" are especially annoying. It would be helpful to go with a more flexible region system, e.g. the user can type whatever region they want instead of choosing from a list of regions.

**Comment by TigerHix** [comment]
Region is a neutral word. It refers to the geographical location only. We can probably refer to the [IANA standard](https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry) for a list of region codes and names (scroll to the bottom).

The problem with the approach you suggested is that we won’t be able to implement region rankings because players can just type whatever they want.

**Comment by Neo-Zhixing** [comment]
We need an auto-complete (like facebook) input box to (slightly) restrict the user selection. Display a list of default options, but if the user is not satisfied, they can still type whatever they want.

Certainly someone, or a good amount of people, would type "Mars", "Republic of California" or something else, but this would only make it more fun.

**Comment by TigerHix** [comment]
Fun is good, but we won't be able to have region rankings then.
