### ISSUE TITLE
Edit zh-fj translation for level_details.json

### ISSUE THREAD

**Issue by stone6666888** [Cytoid/cytoid.io#160]
https://github.com/Cytoid/cytoid.io/blob/7516ff73dcffa436143c95384db9ef07bc91a877/locale/zh-FJ/level_details.json#L15
Suggestion:"Cytoid关卡"⇒"紫薯布丁"
Ignore it if you haven't spare time,just a small detail,thanks

**Comment by Teages** [comment]
make a pr to dev brunch if you think it is really import
