### ISSUE TITLE
Enhance tag display

### ISSUE THREAD

**Issue by TigerHix** [Cytoid/cytoid.io#17]
UI: Hide tag field when there are no tags.

Data consistency: @Neo-Zhixing Some levels happen to have empty tags (""). See /levels/arcs.mkdr. Was there a problem when importing the current site data?

**Comment by Neo-Zhixing** [comment]
This is a data migration problem.

Dirty fix:
```sql
UPDATE levels SET tags='{}' where tags='{""}';
```
