### ISSUE TITLE
Post system

### ISSUE THREAD

**Issue by TigerHix** [Cytoid/cytoid.io#24]
Need more discussion on this one.

**Comment by Neo-Zhixing** [comment]
We can either integrate with a CMS system (more complicated) or build another microservice detached from the main apis.

**Comment by TigerHix** [comment]
Integrating with a boneless CMS like Directus will be a good choice. IIRC Directus can store the posts in markdown, so if we ever need to get rid of it the data migration can be easily done.

**Comment by Neo-Zhixing** [comment]
I would prefer a headless CMS written in node.js (in case we ever need to customize this CMS system), but Directus would work just fine.

Authentication would be a difficulty when integrating with a CMS system.

**Comment by Neo-Zhixing** [comment]
It looks like Directus doesn't support PostgreSQL but they're working on it...
https://twitter.com/directus/status/1083050622864232448?lang=en

**Comment by Neo-Zhixing** [comment]
Some alternatives:
https://keystonejs.com/
https://strapi.io/

**Comment by Neo-Zhixing** [comment]
Upon investigation, I now believe keystone.js is the perfect fit for this job. However, the keystone dev team is now in the progress of rewriting the entire project for their new v5 version. I think we can wait on this a bit longer until keystone v5 reaches beta.
