### ISSUE TITLE
Switching between levels in Level Detail page

### ISSUE THREAD

**Issue by TigerHix** [Cytoid/cytoid.io#26]
Press left or right arrow keys or click on the buttons to go to the next level / prev level in the list user is previously browsing from. For instance, if player is browsing a collection previously, they will navigate to the next/prev level in the collection. If player is browsing some search results previously, they will navigate to the next/prev level in the search results.

May require vuex for global state storage?

**Comment by Neo-Zhixing** [comment]
Vuex would be required.
A good way for doing this would be maintaining a "levelContext" in vuex which is a list of levels.

**Comment by TigerHix** [comment]
Exactly. The list needs to contain the level ids only.
