### ISSUE TITLE
Current visibility should be selected and disabled to prevent confusion

### ISSUE THREAD

**Issue by TigerHix** [Cytoid/cytoid.io#35]
![image](https://user-images.githubusercontent.com/3406505/59576657-8b663d80-908e-11e9-93b3-fc951dae4994.png)

The current visibility should be highlighted and disabled in the dropdown.

**Comment by TigerHix** [comment]
(Maybe just use Select instead of Dropdown)

**Comment by Neo-Zhixing** [comment]
Resolved by using Select.
