### ISSUE TITLE
Minor feature suggestions for the studio

### ISSUE THREAD

**Issue by 2394425147** [Cytoid/cytoid.io#41]
As you know, there's been a ton of unfair ratings on some charts which a part of the fanbase didn't like (whether it's because of their impression on the charter, or it's due to their own understanding/playing of the chart), and there have been a few mentions of this topic since I last opened the community charters' QQ group chat. If you don't mind, please consider these suggestions:

Rating management, allowing charters to view who rated their levels;
Prompt to leave a comment (review), when any user rates a level with less than a set amount of stars, there could be a dialog asking for user input.
Reorganize elements on the level details page, the current user interface might lead to users' ignorance of some information, like the comments section. I was thinking of something like this...?
![concept](https://user-images.githubusercontent.com/39264547/74634619-33dd1c00-519f-11ea-8a3f-761d67bd56aa.png)

It would be cool if these get implemented, and thanks again for making cytoid.io!

**Comment by Neo-Zhixing** [comment]
Thank you for your suggestions.

As an response to this, I believe that the rating system loses its value when it's no longer anonymous. However, there are ways to make the current system better. 

When a user decides to leave a negative rating, they either have a reason, or they don't. So I think prompting the user to give a comment is a fantastic way to make the communications better. The lower the rating, the longer he/she has to type in the comments section. This would also discourage users to give low ratings without justified reasons. So, the idea you proposed actually make a lot of sense.

To implement this we need to have the comments system in our control. This is going to be implemented soon after we migrate from Disqus to a custom-made comments system.
