### ISSUE TITLE
Use DisqusJS and Disqus API Reverse Proxy for comment rendering in China

### ISSUE THREAD

**Issue by ZeroAurora** [Cytoid/cytoid.io#42]
https://github.com/SukkaW/DisqusJS provides an easy way to render Disqus comments using Disqus API. Using a Reverse Proxy can make comments readable by Chinese users.

**Comment by Neo-Zhixing** [comment]
This could be a good idea, but since we already have plans to implement a custom comments system, it might not be worthwhile to set this up right now.
