### ISSUE TITLE
Regex error of uploading a file

### ISSUE THREAD

**Issue by cheny0y0** [Cytoid/cytoid.io#68]
![2347BC2A-1B72-41CD-92BE-4DD32DD39354](https://user-images.githubusercontent.com/66211043/100090963-f4aacc80-2e8e-11eb-8ee1-a6aa504bd996.jpeg)
It's a **fatal** error that was not listed in wiki.

**Comment by Neo-Zhixing** [comment]
Thanks for the feedback! I have added this entry to the [wiki](https://github.com/Cytoid/cytoid.io/wiki/Level-upload-error-self-diagnose).

This is essentially saying your level id must be following a specific format: lowercase letters or numbers connected by ".", "-" or "_".
