### ISSUE TITLE
Mail confirm link returns 404 - token does not exist

### ISSUE THREAD

**Issue by Sodium-Aluminate** [Cytoid/cytoid.io#87]
![Screenshot_20210518-160003_Chrome_Canary](https://user-images.githubusercontent.com/38349409/118614462-5b7fc180-b7f2-11eb-9af3-f0bbaf3d2f10.png)

复现方法
在[设置](https://cytoid.io/settings/account)界面添加一个新邮箱

收到邮件并点击 confirm 或下方链接
访问得到报错 JSON

**Comment by Neo-Zhixing** [comment]
经过尝试，无法复现这个错误。
请问您收到邮件之前，等待了大概多长时间呢？

**Comment by Sodium-Aluminate** [comment]
> 经过尝试，无法复现这个错误。
> 请问您收到邮件之前，等待了大概多长时间呢？

不到一分钟就收到邮件了
算上复制到浏览器不超过五分钟。

顺便一提即使返回了 404 但邮件验证依旧成功了。

**Comment by Teages** [comment]
看起来它无法被复现, 请于再次遇到此问题时重新打开
