### ISSUE TITLE
Failed to upload Cytoid level: Request failed with status code 500

### ISSUE THREAD

**Issue by JerryHan3** [Cytoid/cytoid.io#88]
Tried to upload a Cytoid level file today but failed with the code: Request failed with status code 500. 

This issue happened on [cytoid.cn](cytoid.cn) and can be triggered both when upload a new level and update an existing level. 

![image](https://user-images.githubusercontent.com/63506570/118797106-d0c0c480-b8ce-11eb-849b-ad24547ad48e.png)

**Comment by JerryHan3** [comment]
Also when I tried to visit [cytoid.io](cytoid.io) with proxy it came back with an 500 error. 

![image](https://user-images.githubusercontent.com/63506570/118797441-2b5a2080-b8cf-11eb-9077-904b2f2b88b7.png)

**Comment by SketchySketch** [comment]
I have the same problem too. It seemed that there's something to do with api.cytoid.cn.

**Comment by Neo-Zhixing** [comment]
We're no longer maintaining cytoid.cn due to regulatory concerns . Please let us know if you get this error on cytoid.io.
